name: Kolint Lint

on: push

jobs:
  kotlin-lint-job:
    name: Kotlin Lint Job
    runs-on: ubuntu-latest
    steps:
      # Checkout the latest commit
      - name: Checkout
        uses: actions/checkout@v2

      # Access READ ACCESS TOKEN
      - name: Decode credentials.properties
        env:
          API_KEY: ${{ secrets.READ_ACCESS_TOKEN }}
        run: echo read_access_token=\"$READ_ACCESS_TOKEN\" > ./credentials.properties

      # Kotlin Lint Check
      - name: Ktlint check
        run: ./gradlew ktlintCheck